networks:
  local_network:

services:
  api:
    image: tax-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on: [postgres]
    environment:
      PORT: 8080
      DATABASE_URL: host=postgres port=5432 user=postgres password=postgres dbname=ktaxes sslmode=disable
      ADMIN_USERNAME: adminTax
      ADMIN_PASSWORD: admin!
    ports:
      - "8080:8080"
    networks:
      - local_network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - local_network
